version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate the proto files"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative

  migrate:
    aliases:
      - mig
    desc: "Migrate the database"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migration-path=./migrations

  start:
    aliases:
      - start
    desc: "Start the server"
    cmds:
      - go run  ./cmd/sso/ --config=./config/local.yaml 
